import pyautogui
import time
#
# # print (pyautogui.KEYBOARD_KEYS)
#
# print (pyautogui.position())
#
pyautogui.alert('O código vai começar')
pyautogui.PAUSE = 0.3

# ###________________________________Pagina 01_________________________##
i = int(1)

while i < 2:
 pyautogui.moveTo(758,147)
 pyautogui.click(clicks=1)
 pyautogui.press('1')
 pyautogui.hotkey('shift','winleft','s')
 time.sleep(0.3)
 pyautogui.moveTo(723,275)
 time.sleep(0.3)
 pyautogui.mouseDown()
 time.sleep(0.3)
 pyautogui.moveTo(1171,909)
 time.sleep(0.3)
 pyautogui.mouseUp()
 time.sleep(0.3)
 pyautogui.moveTo(3192, 827)
 time.sleep(0.3)
 pyautogui.click(clicks = 2)
 time.sleep(0.3)
 pyautogui.write('t')
 pyautogui.press('enter')
 time.sleep(0.3)
 pyautogui.moveTo(3863,310)
 time.sleep(0.3)
 pyautogui.click()
 time.sleep(0.3)
 pyautogui.hotkey('ctrl','v')
 time.sleep(0.3)
 i += 1
 pyautogui.moveTo(758,147)
 pyautogui.click(clicks=2)
 pyautogui.write('i')
 pyautogui.press('enter')
 pyautogui.hotkey('shift','winleft','s')
 time.sleep(0.3)
 pyautogui.moveTo(723,275)
 time.sleep(0.3)
 pyautogui.mouseDown()
 time.sleep(0.3)
 pyautogui.moveTo(1171,909)
 time.sleep(0.3)
 pyautogui.mouseUp()
 time.sleep(0.3)
 pyautogui.moveTo(3863,310)
 time.sleep(0.3)
 pyautogui.click()
 time.sleep(0.3)
 pyautogui.hotkey('ctrl','v')
 time.sleep(0.3)
 i += 1
 pyautogui.moveTo(758,147)
 pyautogui.click(clicks=2)
 pyautogui.write('i')
 pyautogui.press('enter')
 pyautogui.hotkey('shift','winleft','s')
 time.sleep(0.3)
 pyautogui.moveTo(723,275)
 time.sleep(0.3)
 pyautogui.mouseDown()
 time.sleep(0.3)
 pyautogui.moveTo(1171,909)
 time.sleep(0.3)
 pyautogui.mouseUp()
 time.sleep(0.3)
 pyautogui.moveTo(3863,310)
 time.sleep(0.3)
 pyautogui.click()
 time.sleep(0.3)
 pyautogui.hotkey('ctrl','v')
 time.sleep(0.3)
 i += 1
 pyautogui.moveTo(758,147)
 pyautogui.click(clicks=2)
 pyautogui.write('i')
 pyautogui.press('enter')
 pyautogui.hotkey('shift','winleft','s')
 time.sleep(0.3)
 pyautogui.moveTo(723,275)
 time.sleep(0.3)
 pyautogui.mouseDown()
 time.sleep(0.3)
 pyautogui.moveTo(1171,909)
 time.sleep(0.3)
 pyautogui.mouseUp()
 time.sleep(0.3)
 pyautogui.moveTo(3863,310)
 time.sleep(0.3)
 pyautogui.click()
 time.sleep(0.3)
 pyautogui.hotkey('ctrl','v')
 i += 1
 t = t + 1

pyautogui.alert('O código terminou')
